name: Docker Publish (on Release)

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: release-please-demo   # <-- change to your image name (repo can differ)

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive version from release tag
        id: v
        run: |
          RAW_TAG="${{ github.event.release.tag_name }}"
          # strip leading v if present
          VERSION="${RAW_TAG#v}"
          MAJOR="$(echo "$VERSION" | cut -d. -f1)"
          MINOR="$(echo "$VERSION" | cut -d. -f2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "major=$MAJOR"     >> $GITHUB_OUTPUT
          echo "minor=$MINOR"     >> $GITHUB_OUTPUT

      - name: Compute lowercase owner & full image name
        id: repo
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lower=$OWNER_LOWER" >> $GITHUB_OUTPUT
          echo "image=${{ env.REGISTRY }}/${OWNER_LOWER}/${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT

      - name: Set Docker tag list
        id: tags
        run: |
          IMAGE="${{ steps.repo.outputs.image }}"
          VERSION="${{ steps.v.outputs.version }}"
          MAJOR="${{ steps.v.outputs.major }}"
          MINOR="${{ steps.v.outputs.minor }}"

          TAGS="${IMAGE}:${VERSION},${IMAGE}:${MAJOR}.${MINOR},${IMAGE}:${MAJOR},${IMAGE}:latest"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Set up QEMU (for multi-arch; optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo.outputs.owner_lower }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},source=event
            type=semver,pattern={{major}}.{{minor}},source=event
            type=semver,pattern={{major}},source=event
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate summary
        run: |
          echo "## 🚢 Docker Publish Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image Base:** \`${{ steps.repo.outputs.image }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tags Pushed:**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.tags.outputs.tags }}" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
